### ISSUE TITLE
Feature: Support Data Source - Trino

### ISSUE THREAD

**Issue by andreashimin** [Canner/WrenAI#492]
**Description**
This feature allows users to connect Trino as a data source in connection setup.
In setup connection UI, it needs to provide these inputs below:
- Display name
- Host
- Port
- Catalog
- Schema
- Username 
- Password

Refer to:
https://github.com/Canner/wren-engine/pull/662

**Additional context**
- Trino's Logo (Please download this & put in `./public/images/dataSource/**`)
![trino](https://github.com/Canner/WrenAI/assets/9657305/aecc6d46-bdf9-4b96-bc30-5e2329c3c598)

- UI Reference
  <img width="500" alt="image" src="https://github.com/Canner/WrenAI/assets/9657305/f5de2e26-7c21-42ed-adca-fb3eb1e98834">
  <img src="https://github.com/Canner/WrenAI/assets/9657305/4b00d8aa-89db-44ff-8b93-cab65bdc78d9" width="500" />

**Comment by onlyjackfrost** [comment]
Things to do in the Wren-UI Backend will be
### Allow create Trino data source from the client-side
- modify graphql schema
- extend the datasource.ts  to store connection info properly

### Integrate with the Ibis server 
- extend the ibisAdaptor.ts to connect to ibis server

reference PR: https://github.com/Canner/WrenAI/pull/481

Things to do in the Wren-Engine will be
### Implement (POST) /trino/metadata/tables API
This API should fetch all the tables in the schema specified by the user

### Implement (POST) /trino/metadata/constraints API
This API should fetch all the constraints in the schema specified by the user
Currently, we use constraints as our recommended relation between models
(Note): Since the relation type (one-to-many, many-to-one, ...) can not be detected without fetching the user's data, we hard-code the relation type to one-to-many and let the user change it 

reference PR: https://github.com/Canner/wren-engine/pull/648

**Comment by himanshu634** [comment]
@andreashimin Can you assign it to me?

**Comment by andreashimin** [comment]
Completed in #535
